library(Seurat)
library(patchwork)
library(cowplot)
library(data.table)
library(dplyr)
library(ggplot2)
library(repr)
library(batchelor)
library(glmGamPoi)
library(stringr)
library(tibble)
library(DoubletFinder)
library(SeuratWrappers)

load("/node200data/FTC/data/230731_FTC_GEX1_draft_annotation.RData")
DimPlot(FTC_GEX1, label = T, label.size = 4, split.by = "tissue_type")
View(FTC_GEX1@meta.data)
idents <- c("arterial endo","unknown endo","lymphatic endo","angiogenic endo?","venous endo","tip-like endo")
DotPlot(FTC_GEX1, features = c("VEGFA","PDGFA","PDGFB","VEGFR1","VEGFR2","eNOS"," VEGFR3"),idents = idents, split.by = "tissue_type",scale = TRUE)
DotPlot(FTC_GEX1, features = c("VEGFA","PDGFA","PDGFB","VEGFR1","VEGFR2","eNOS"," VEGFR3"),idents = idents, scale = TRUE)

RidgePlot(FTC_GEX1, features = c("VEGFA","PDGFA","PDGFB","VEGFR1","VEGFR2","eNOS"," VEGFR3"), ncol = 2)
FeaturePlot(FTC_GEX1, features = c("VEGFA","PDGFA","PDGFB","VEGFR1","VEGFR2","eNOS"," VEGFR3"),split.by = "tissue_type")
FTC_GEX_endo <- WhichCells(FTC_GEX1, ident = idents)
FTC_GEX_endo <- subset(FTC_GEX1, cells = FTC_GEX_endo)
FeaturePlot(FTC_GEX_endo, features = c("VEGFA","VEGFC","PDGFA","PDGFB","VEGFR1","VEGFR2","eNOS"," VEGFR3"),split.by = "tissue_type")
DotPlot(FTC_GEX_endo, features = c("VEGFA","VEGFC","PDGFA","PDGFB","VEGFR1","VEGFR2","eNOS"," VEGFR3"), idents = c("arterial endo", "lymphatic endo"),split.by = "tissue_type",scale = TRUE)
DotPlot(FTC_GEX_endo, features = c("VEGFA","VEGFC","PDGFA","PDGFB","VEGFR1","VEGFR2","eNOS"," VEGFR3"), idents = c("arterial endo", "lymphatic endo"),group.by = "tissue_type",scale = TRUE) & theme(axis.title.x.right = element_text(size = 5))

idents <- c("PPARG+ mac?","C1QC+ mac?","C1QC/LYVE1+ mac","GPNMB/CCL18/SPP1+ mac","CX3CR1/FN1+ mac","NLRP3/IL1B+ mac")
FTC_GEX_mac <- WhichCells(FTC_GEX1, ident = idents)
FTC_GEX_mac <- subset(FTC_GEX1, cells = FTC_GEX_mac)
TAM_marker <- c("CD163","CD68","CD206","VEGFA","IL10","dectin1","NOS2"," MGL-1","CCR2","PDL2","CD40"," CCL2","PDGFB")
M2_marker <- c("CSF1R","CD115","ARG1","MRC1","CD209","FIZZ1","TGFb","IL1","IL6","ECM","TNFa","dectin1","AXL","ECM","NO","CCL18","MGL1","GR")
M1_marker <- c("IL1B","NOS2","TLR2","CD86")

FeaturePlot(FTC_GEX_mac, features = TAM_marker,split.by = "tissue_type")
DotPlot(FTC_GEX_mac, features = TAM_marker, group.by = "tissue_type",scale = TRUE)

FeaturePlot(FTC_GEX_mac, features = M2_marker,split.by = "tissue_type")
DotPlot(FTC_GEX_mac, features = c("CSF1R","ARG1","MRC1","CD209","IL6","AXL","CCL18","LPS"), group.by = "tissue_type",scale = TRUE)

FeaturePlot(FTC_GEX_mac, features = M1_marker,split.by = "tissue_type")
DotPlot(FTC_GEX_mac, features = M1_marker, group.by = "tissue_type",scale = TRUE)

-----------------------------------------------------------------------------------------------------------------
DimPlot(FTC_GEX1, label = T, split.by = "tissue_type")
DimPlot(FTC_GEX1, label = T, group.by = "tissue_type")

Tcellsubtypes <- c("CD8 Naive","unknown unconv. T","CD8 Trm","CD4 unknown","CD4 Naive","CD8 Tex","CD4 Tex","Treg","CD8 eff","CD4 Trm","CD4 Tcm","CD8 Tem", "NKT")
Tcell <- WhichCells(FTC_GEX1, idents = Tcellsubtypes)
Bcell <- WhichCells(FTC_GEX1, idents = "B")
PC <- WhichCells(FTC_GEX1, idents = "plasma")
NK <- WhichCells(FTC_GEX1, idents = "NK")
ML <- c("pDC","PPARG+ mac?","CD16 Mono","CD14 Mono","LAMP3+ cDC","cDC","C1QC+ mac?","C1QC/LYVE1+ mac","GPNMB/CCL18/SPP1+ mac","CX3CR1/FN1+ mac","NLRP3/IL1B+ mac")
Myeloid <- WhichCells(FTC_GEX1, idents = ML)

saveRDS(Tcell, file = '/home/jurny0402/FTC/data/231116_whichcells_CD45pos/231116_FTC_GEX1_WhichCells=Tcell.rds')
saveRDS(Bcell, file = '/home/jurny0402/FTC/data/231116_whichcells_CD45pos/231116_FTC_GEX1_WhichCells=Bcell.rds')
saveRDS(PC, file = '/home/jurny0402/FTC/data/231116_whichcells_CD45pos/231116_FTC_GEX1_WhichCells=PC.rds')
saveRDS(NK, file = '/home/jurny0402/FTC/data/231116_whichcells_CD45pos/231116_FTC_GEX1_WhichCells=NK.rds')
saveRDS(Myeloid, file = '/home/jurny0402/FTC/data/231116_whichcells_CD45pos/231116_FTC_GEX1_WhichCells=Myeloid.rds')

DimPlot(FTC_GEX1, label = TRUE, label.size = 4, cells.highlight = Myeloid, sizes.highlight = .1, split.by = "tissue_type")
